env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {
  indent: error,
  import/no-unresolved: 'off',
  import/no-extraneous-dependencies: 'off',
  import/order: 'off',
  vue/multi-word-component-names: 'off',
  vue/no-v-text-v-html-on-component: 'off',
  import/prefer-default-export: 'off',
  vue/valid-v-for: 'off'
}
